// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHi6hJswohK-wgD8Mbuhb8PjOFLQWxzpE',
    appId: '1:856040604769:web:1c1b4263e688dd7fc01620',
    messagingSenderId: '856040604769',
    projectId: 'mad-labs-f6dab',
    authDomain: 'mad-labs-f6dab.firebaseapp.com',
    storageBucket: 'mad-labs-f6dab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSpH0fvN2IspGZuDs1KXvxCAyx1ug43w',
    appId: '1:856040604769:android:ff127cff81fc44bbc01620',
    messagingSenderId: '856040604769',
    projectId: 'mad-labs-f6dab',
    storageBucket: 'mad-labs-f6dab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGUCO9k8rig8YsR4nBUK0hJKLUSrjJVw',
    appId: '1:856040604769:ios:05fce38b0596e575c01620',
    messagingSenderId: '856040604769',
    projectId: 'mad-labs-f6dab',
    storageBucket: 'mad-labs-f6dab.appspot.com',
    iosBundleId: 'com.example.chatscreenui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGUCO9k8rig8YsR4nBUK0hJKLUSrjJVw',
    appId: '1:856040604769:ios:05fce38b0596e575c01620',
    messagingSenderId: '856040604769',
    projectId: 'mad-labs-f6dab',
    storageBucket: 'mad-labs-f6dab.appspot.com',
    iosBundleId: 'com.example.chatscreenui',
  );
}

